# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: []

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9

      - name: boost
        run: |
          sudo apt install -y libboost1.65-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install package
        run: pip install -e .

      - name: Test with pytest
        run: |
          pytest
