# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9

      - name: boost
        run: |
          sudo apt install -y libboost1.65-dev

      # - uses: actions/cache@master
      #   id: cache
      #   with:
      #     path: ${{ env.pythonLocation}}/lib/python3.6/site-packages/*
      #     key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
      #     restore-keys: |
      #       ${{ runner.os }}-pip-
      #       ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: py-opt-control
        run: |
          git clone https://github.com/jpaulos/opt_control.git
          cd opt_control/python
          make
          pip install -e .

      - name: Install package
        run: pip install -e .

      # - name: Lint with flake8
      #   run: |
      #     # stop the build if there are Python syntax errors or undefined names
      #     # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #     flake8 motion_primitives_py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
