name: Build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-18.04
    container: ros:melodic

    steps:
      - name: install apt deps
        run: |
          apt-get update
          apt-get install -y libeigen3-dev libtbb-dev libgtest-dev

      - name: checkout motion_primitives
        uses: actions/checkout@v2
        with:
          path: src/motion_primitives

      - name: checkout planning_ros_msgs
        uses: actions/checkout@v2
        with:
          repository: ljarin/planning_ros_msgs
          path: src/planning_ros_msgs

      - name: checkout nlohmann json
        uses: actions/checkout@v2
        with:
          repository: nlohmann/json
          path: src/motion_primitives/external/json

      - name: checkout googletest
        uses: actions/checkout@v2
        with:
          repository: google/googletest
          path: src/motion_primitives/external/googletest

      - name: checkout ruckig
        uses: actions/checkout@v2
        with:
          repository: ljarin/ruckig
          path: src/motion_primitives/external/ruckig
          ref: laura_dev

      - name: checkout pybind
        uses: actions/checkout@v2
        with:
          repository: pybind/pybind11
          path: src/motion_primitives/external/ruckig/pybind11

      - name: build googletest
        shell: bash
        run: |
          cd src/motion_primitives/external/googletest
          mkdir build
          cd build
          cmake ..
          make install

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: "3.20.x"

      - name: catkin_make
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin_make -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: catkin_make run_tests
        shell: bash
        run: |
          source /opt/ros/$ROS_DISTRO/setup.bash
          catkin_make run_tests
          catkin_test_results

      - name: Set up Python 3.6.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.6.9

      - name: boost
        run: |
          sudo apt install -y libboost1.65-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install local ruckig
        run: |
          cd src/motion_primitives/external/ruckig
          pip install .

      - name: Install package
        run: |
          cd src/motion_primitives
          pip install -e .

      - name: Test with pytest
        shell: bash
        run: |
          . devel/setup.bash
          cd src/motion_primitives/motion_primitives_py
          pytest
